# Usa la imagen base de Python
FROM python:latest

# Copia el script al contenedor
COPY Feature_Communicator/Feature_communicator_http.py /app/Feature_Communicator/Feature_communicator_http.py
COPY ../requirements.txt /app/requirements.txt

# Establece el directorio de trabajo
WORKDIR /app

# Instala las dependencias necesarias, como OpenCV
RUN apt-get update
RUN apt install -y libgl1-mesa-glx
RUN pip install -r requirements.txt

# Establece las variables de entorno
ENV own_host="0.0.0.0" \
    own_port="5001" \
    ArUco_Tracker_ip="0.0.0.0" \
    ArUco_Tracker_port="5002"

# Abrimos el puerto 5001 del contenedor para permitir las comunicaciones
EXPOSE 5001

# Comando para ejecutar el script
CMD ["python", "Feature_Communicator/Feature_communicator_http.py"]