# Usa la imagen base de Python
FROM python:latest

# Copia el script al contenedor
COPY Filter_Selector/Filter_selector_http.py /app/Filter_Selector/Filter_selector_http.py
COPY ../requirements.txt /app/requirements.txt

# Establece el directorio de trabajo
WORKDIR /app

# Instala las dependencias necesarias, como OpenCV
RUN apt-get update
RUN apt install -y libgl1-mesa-glx
RUN pip install -r requirements.txt

# Establece las variables de entorno
ENV own_host="0.0.0.0" \
    own_port="5000" \
    Visualizer_ip="0.0.0.0" \
    Visualizer_port="5003"

# Abrimos el puerto 5000 del contenedor para permitir las comunicaciones
EXPOSE 5000

# Comando para ejecutar el script
CMD ["python", "Filter_Selector/Filter_selector_http.py"]
