# Usa la imagen base de Python
FROM python:latest

# Copia el script al contenedor
COPY Video_Capturer/Video_capturer_http.py /app/Video_capturer_http.py
COPY ../requirements.txt /app/requirements.txt

# Establece el directorio de trabajo
WORKDIR /app

# Instala las dependencias necesarias, como OpenCV
RUN apt-get update
RUN apt install -y libgl1-mesa-glx
RUN pip install -r requirements.txt

# Establece las variables de entorno
ENV Feature_Communicator_ip="127.0.0.1" \
    Feature_Communicator_port="5001" \
    Filter_Selector_ip="127.0.0.1" \
    Filter_Selector_port="5000"

# Abrimos el puerto 5000 del contenedor para permitir las comunicaciones
EXPOSE 5000 5001

# Comando para ejecutar el script
CMD ["python", "Video_capturer_http.py"]
