# video-generator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-capturer
spec: # Configuracion del deployment
  replicas: 1 # Indica el número deseado de réplicas del conjunto de pods que el Deployment debe mantener en funcionamiento en todo momento.
  selector: # Especifica cómo el Deployment encuentra qué pods administrar. 
    matchLabels: # Define las etiquetas que deben coincidir con las etiquetas de los pods para que sean seleccionados por este Deployment. 
      app: video-capturer
  template: # Define la plantilla para crear nuevos pods administrados por el Deployment.
    metadata:
      labels: # Especifica las etiquetas que se asignarán a los pods creados por este Deployment.
        app: video-capturer
    spec:
      containers:
      - name: video-capturer # Nombre del contenedor
        volumeMounts:
          - mountPath: /dev/video0
            name: dev-video0
        image: enriquelpzenc/video-capturer_http:latest
        env: # Variables del servicio.
          - name: Feature_Communicator_ip
            value: "192.168.49.2"
          - name: Feature_Communicator_port
            value: "30001"
          - name: Filter_Selector_ip
            value: "192.168.49.2"
          - name: Filter_Selector_port
            value: "30000"
      volumes: # Es una lista de volúmenes que se montarán en el contenedor dentro del Pod.
        - name: dev-video0 # Es el nombre del volumen.
          hostPath: # Especifica que el volumen se montará desde una ruta del sistema de archivos del nodo.
            path: /dev/video0 # Especifica la ruta del sistema de archivos del nodo desde la que se montará el volumen en el contenedor.
---

---