# video-generator-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-capturer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-capturer
  template:
    metadata:
      labels:
        app: video-capturer
    spec:
      containers:
      - name: video-capturer
        volumeMounts:
          - mountPath: /dev/video0
            name: dev-video0
        image: enriquelpzenc/video-capturer_http:latest
        env:
          - name: Feature_Communicator_ip
            value: 0.0.0.0
          - name: Feature_Communicator_port
            value: 5001
          - name: Filter_Selector_ip
            value: 0.0.0.0
          - name: Filter_Selector_port
            value: 5000
      volumes:
        - name: dev-video0
          hostPath:
            path: /dev/video0
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: video-capturer
spec:
  selector:
    app: video-capturer
  ports:
    - protocol: TCP
      targetPort: 5000
---