# visualizer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visualizer
  template:
    metadata:
      labels:
        app: visualizer
    spec:
      containers:
      - name: visualizer
        image: enriquelpzenc/visualizer_http:latest
        ports:
        - containerPort: 5003
        env:
          - name: own_host
            value: 0.0.0.0
          - name: own_port
            value: 5003
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: visualizer
spec:
  selector:
    app: visualizer
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
---